version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysqldb 
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    command: --default-authentication-plugin=mysql_native_password && --init-file /data/application/init.sql 
    restart: always
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/setup.sql        
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ROOT_HOST=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  dbadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: dbadmin
    environment:
       PMA_ARBITRARY: 1 
    ports:
      - 8081:80
    depends_on:
      - mysqldb
