version: "3.7"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=root
    ports:
      - 3306:3306

  phpserver:
    image: php:latest
    container_name: phpserver
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysqldb

networks:
  default:
    external: false
