version: "2"
services:
  webserver:
    image: php:latest 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - test

networks:
  test:
    external: true
