name: Publish Docker image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERTOKEN_USERNAME }}
          password: ${{ secrets.DOCKERTOKEN_TOKEN }}
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/server
