name: Simple github action for FIGLET 

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: FIGLET
        run: sudo apt install figlet && figlet saurabh && figlet server
