<?php
/*
//auth 0846c1af6af09178fdced98e380834a7
//sid AC2be8481cceb70b8551d176fd0e3d412e
// From URL to get webpage contents.
$url = "https://www.geeksforgeeks.org/";

// Initialize a CURL session.
$ch = curl_init();

// Return Page contents.
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

//grab URL and pass it to the variable.
curl_setopt($ch, CURLOPT_URL, $url);

$result = curl_exec($ch);

echo $result;
*/

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$otp = "567849";
curl_setopt($ch, CURLOPT_URL, 'https://api.mailgun.net/v3/sandbox7d6345b381e54885939a4d02955bb920.mailgun.org/messages');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$post = array(
    'from' => 'saurabh45215@gmail.com',
    'to' => 'saurabh45215@gmail.com',
    'subject' => 'Hello',
    'text' => 'hey there buddy '.$otp
);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_USERPWD, 'api' . ':' . '537b5ab9dd8806c4cb96bbf3fd98212d-07a637b8-c26811d1');

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
?>
+18085635146